### ISSUE TITLE
can not install in Visual Studio 2019

### ISSUE THREAD

**Issue by PhysicsPlasma** [michaelkonecny/vs-fortran-ls-client#1]
I have tried to install the `vsix` in Visual Studio 2019, but the installation fails, can you help us to fix it? Thanks!

2019/7/15 10:47:43 - Microsoft VSIX Installer
2019/7/15 10:47:43 - -------------------------------------------
2019/7/15 10:47:43 - vsixinstaller.exe version:
2019/7/15 10:47:43 - 16.1.3132
2019/7/15 10:47:43 - -------------------------------------------
2019/7/15 10:47:43 - Command line parameters:
2019/7/15 10:47:43 - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\OneDrive\Download\Fortran.IntelliSense.vsix
2019/7/15 10:47:43 - -------------------------------------------
2019/7/15 10:47:43 - Microsoft VSIX Installer
2019/7/15 10:47:43 - -------------------------------------------
2019/7/15 10:47:43 - Initializing Install...
2019/7/15 10:47:44 - Extension Details...
2019/7/15 10:47:44 - 	Identifier         : FortranLanguageClient
2019/7/15 10:47:44 - 	Name               : Fortran IntelliSense
2019/7/15 10:47:44 - 	Author             : Michael Konečný
2019/7/15 10:47:44 - 	Version            : 0.1
2019/7/15 10:47:44 - 	Description        : Adds IntelliSense for fortran using Chris Hansen's Fortran Language Server
 (https://github.com/hansec/fortran-language-server).

2019/7/15 10:47:44 - 	Locale             : en-US
2019/7/15 10:47:44 - 	MoreInfoURL        : https://github.com/michaelkonecny/vs-fortran-ls-client
2019/7/15 10:47:44 - 	InstalledByMSI     : False
2019/7/15 10:47:44 - 	SupportedFrameworkVersionRange : [4.5,)
2019/7/15 10:47:44 - 
2019/7/15 10:47:44 - 	SignatureState     : Unsigned
2019/7/15 10:47:44 - 	Supported Products : 
2019/7/15 10:47:44 - 		Microsoft.VisualStudio.Community
2019/7/15 10:47:44 - 			Version : [15.0]
2019/7/15 10:47:44 - 
2019/7/15 10:47:44 - 	References         : 
2019/7/15 10:47:44 - 		-------------------------------------------------------
2019/7/15 10:47:44 - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
2019/7/15 10:47:44 - 		Name         : Visual Studio MPF 15.0
2019/7/15 10:47:44 - 		Version      : [15.0]
2019/7/15 10:47:44 - 		MoreInfoURL  : 
2019/7/15 10:47:44 - 		Nested       : No
2019/7/15 10:47:44 - 
2019/7/15 10:47:44 - 	Prerequisites      : 
2019/7/15 10:47:44 - 		-------------------------------------------------------
2019/7/15 10:47:44 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2019/7/15 10:47:44 - 		Name         : Visual Studio core editor
2019/7/15 10:47:44 - 		Version      : [15.0,16.0)
2019/7/15 10:47:44 - 
2019/7/15 10:47:44 - Signature Details...
2019/7/15 10:47:44 - 	Extension is not signed.
2019/7/15 10:47:44 - 
2019/7/15 10:47:44 - Searching for applicable products...
2019/7/15 10:47:44 - Found installed product - Global Location
2019/7/15 10:47:44 - Found installed product - Visual Studio Community 2019
2019/7/15 10:47:44 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by michaelkonecny** [comment]
Hi, I haven't switched to VS2019 yet, so I can't build a vsix for it now, but I will be switching in about two months.

However, feel free to fork the source code and update it for VS2019 yourself. It shouldn't bee too difficult.
